import { NextResponse } from "next/server";
import { readFileSync } from "fs";
import { join } from "path";

interface BusStop {
  name: string;
  landmarks: string[];
  lat?: number;
  lng?: number;
}

interface LGA {
  name: string;
  description: string;
  busStops: BusStop[];
}

interface CachedData {
  lastUpdated: string;
  source: string;
  totalLGAs: number;
  totalBusStops: number;
  lgas: LGA[];
}

export async function GET() {
  try {
    // Read cached data from file (generated by GitHub Actions)
    const dataPath = join(process.cwd(), 'data', 'bus-stops.json');
    const fileData = readFileSync(dataPath, 'utf-8');
    const cachedData: CachedData = JSON.parse(fileData);

    return NextResponse.json({
      success: true,
      lgas: cachedData.lgas,
      totalBusStops: cachedData.totalBusStops,
      source: cachedData.source,
      cachedAt: cachedData.lastUpdated,
    });

  } catch (error) {
    console.error("Error reading cached bus stop data:", error);
    
    // Fallback to empty response
    return NextResponse.json(
      { 
        success: false, 
        error: "Failed to load bus stop data",
        lgas: [],
      },
      { status: 500 }
    );
  }
}
